vsim -gui work.processor
add wave -position insertpoint  \
sim:/processor/CLK
force -freeze sim:/processor/CLK 1 0, 0 {100 ps} -r 200
mem load -filltype value -filldata 10 -fillradix hexadecimal /processor/instructionMemory/ram(0)
mem load -filltype value -filldata 100 -fillradix hexadecimal /processor/instructionMemory/ram(2)
mem load -filltype value -filldata C912 -fillradix hexadecimal /processor/instructionMemory/ram(16)
mem load -filltype value -filldata 30 -fillradix hexadecimal /processor/instructionMemory/ram(17)
mem load -filltype value -filldata CA12 -fillradix hexadecimal /processor/instructionMemory/ram(18)
mem load -filltype value -filldata 50 -fillradix hexadecimal /processor/instructionMemory/ram(19)
mem load -filltype value -filldata CB12 -fillradix hexadecimal /processor/instructionMemory/ram(20)
mem load -filltype value -filldata 100 -fillradix hexadecimal /processor/instructionMemory/ram(21)
mem load -filltype value -filldata CC12 -fillradix hexadecimal /processor/instructionMemory/ram(22)
mem load -filltype value -filldata 300 -fillradix hexadecimal /processor/instructionMemory/ram(23)
mem load -filltype value -filldata 641E -fillradix hexadecimal /processor/instructionMemory/ram(24)
mem load -filltype value -filldata 991E -fillradix hexadecimal /processor/instructionMemory/ram(25)
mem load -filltype value -filldata 312C -fillradix hexadecimal /processor/instructionMemory/ram(26)
mem load -filltype value -filldata 520 -fillradix hexadecimal /processor/instructionMemory/ram(48)
mem load -filltype value -filldata 821E -fillradix hexadecimal /processor/instructionMemory/ram(49)
mem load -filltype value -filldata 481E -fillradix hexadecimal /processor/instructionMemory/ram(50)
mem load -filltype value -filldata 811E -fillradix hexadecimal /processor/instructionMemory/ram(80)
mem load -filltype value -filldata 931E -fillradix hexadecimal /processor/instructionMemory/ram(81)
mem load -filltype value -filldata 15A4 -fillradix hexadecimal /processor/instructionMemory/ram(82)
mem load -filltype value -filldata CE12 -fillradix hexadecimal /processor/instructionMemory/ram(83)
mem load -filltype value -filldata 200 -fillradix hexadecimal /processor/instructionMemory/ram(84)
mem load -filltype value -filldata 8E1E -fillradix hexadecimal /processor/instructionMemory/ram(85)
mem load -filltype value -filldata 312C -fillradix hexadecimal /processor/instructionMemory/ram(86)
mem load -filltype value -filldata 501E -fillradix hexadecimal /processor/instructionMemory/ram(256)
mem load -filltype value -filldata 0 -fillradix hexadecimal /processor/instructionMemory/ram(257)
mem load -filltype value -filldata AEDE -fillradix hexadecimal /processor/instructionMemory/ram(258)
mem load -filltype value -filldata 481E -fillradix hexadecimal /processor/instructionMemory/ram(512)
mem load -filltype value -filldata 6E1E -fillradix hexadecimal /processor/instructionMemory/ram(513)
mem load -filltype value -filldata 7E1E -fillradix hexadecimal /processor/instructionMemory/ram(514)
mem load -filltype value -filldata 36CC -fillradix hexadecimal /processor/instructionMemory/ram(515)
mem load -filltype value -filldata 581E -fillradix hexadecimal /processor/instructionMemory/ram(516)
mem load -filltype value -filldata 581E -fillradix hexadecimal /processor/instructionMemory/ram(517)
mem load -filltype value -filldata 2668 -fillradix hexadecimal /processor/instructionMemory/ram(768)
mem load -filltype value -filldata 2228 -fillradix hexadecimal /processor/instructionMemory/ram(769)
mem load -filltype value -filldata 701E -fillradix hexadecimal /processor/instructionMemory/ram(770)
mem load -filltype value -filldata 481E -fillradix hexadecimal /processor/instructionMemory/ram(771)
